# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # - before: sudo sh ./.gitpod/setup.sh $GITPOD_GIT_USER_NAME $GITPOD_GIT_USER_EMAIL
  - before: git-crypt unlock ~/git-crypt-key
    # init: mvn package -Dmaven.test.skip.exec
    # command: java -jar target/*.jar

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

image:
  file: .gitpod/Dockerfile

vscode:
  extensions:
    - ckolkman.vscode-postgres