# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: sh ./.gitpod/setup.sh
    # init: mvn package -Dmaven.test.skip.exec
    # command: java -jar target/*.jar

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

# image:
#   file: .gitpod/.gitpod.Dockerfile

vscode:
  extensions:
    - ckolkman.vscode-postgres